# Generated by Django 3.2.7 on 2021-09-04 09:47

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TubeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('xtra_data', models.JSONField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='TubeBatchPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tubes.tubebatch')),
                ('tube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tubes.tube')),
            ],
        ),
        migrations.AddField(
            model_name='tubebatch',
            name='tubes',
            field=models.ManyToManyField(through='tubes.TubeBatchPosition', to='tubes.Tube'),
        ),
    ]
