# Generated by Django 3.2.7 on 2023-01-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubes', '0003_auto_20230119_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tube',
            old_name='tube_id',
            new_name='barcode',
        ),
    ]
