
FILE_HEADER_DATE = 'Date'
FILE_HEADER_TIME = 'Time'
FILE_HEADER_RACKBARCODE = 'Rack barcode'
FILE_HEADER_POSITION = 'Position'
FILE_HEADER_TUBEBARCODE = 'Tube barcode'
FILE_HEADERS = [FILE_HEADER_DATE, FILE_HEADER_TIME, FILE_HEADER_RACKBARCODE, FILE_HEADER_POSITION, FILE_HEADER_TUBEBARCODE]