export const REPLICATION__DUPLICATE = "REPLICATION__DUPLICATE";
export const REPLICATION__TRIPLICATE = "REPLICATION__TRIPLICATE";

export const ACTIVE__REPLICATION__CHOICES = [
  REPLICATION__DUPLICATE,
  REPLICATION__TRIPLICATE,
];

export const DISPLAY__REPLICATION__DUPLICATE = "Duplicate";
export const DISPLAY__REPLICATION__TRIPLICATE = "Triplicate";

export const REPLICATION_DISPLAY_MAPPING = {
  REPLICATION__DUPLICATE: DISPLAY__REPLICATION__DUPLICATE,
  REPLICATION__TRIPLICATE: DISPLAY__REPLICATION__TRIPLICATE,
};

export const RUN_METHOD__EUROFINS = "RUN_METHOD__EUROFINS";
export const RUN_METHOD__SALIVACLEAR = "RUN_METHOD__SALIVACLEAR";

export const ACTIVE__RUN_METHOD__CHOICES = [
  RUN_METHOD__EUROFINS,
  RUN_METHOD__SALIVACLEAR,
];

export const DISPLAY__RUN_METHOD__EUROFINS = "Eurofins";
export const DISPLAY__RUN_METHOD__SALIVACLEAR = "Saliva Clear";

export const RUN_METHOD_DISPLAY_MAPPING = {
  RUN_METHOD__EUROFINS: DISPLAY__RUN_METHOD__EUROFINS,
  RUN_METHOD__SALIVACLEAR: DISPLAY__RUN_METHOD__SALIVACLEAR,
};
