export const REPLICATION__DUPLICATE = "DUPLICATE";
export const REPLICATION__TRIPLICATE = "TRIPLICATE";

export const RUN_METHOD__EUROFINS = "RM__EUROFINS";
export const RUN_METHOD__SALIVACLEAR = "RM__SALIVACLEAR";
