# Generated by Django 3.2.7 on 2022-02-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tubes', '0002_alter_tubebatchposition_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('run_characteristics', models.JSONField()),
                ('well_template', models.JSONField()),
                ('run_file', models.FileField(upload_to='')),
                ('tube_batches', models.ManyToManyField(to='tubes.TubeBatch')),
            ],
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('barcode_data', models.JSONField()),
                ('prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='run.runresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='run.run')),
            ],
        ),
    ]
