# Generated by Django 3.2.7 on 2022-08-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='run_file',
        ),
        migrations.RemoveField(
            model_name='run',
            name='well_template',
        ),
        migrations.CreateModel(
            name='RunConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_template', models.JSONField()),
                ('run_file', models.FileField(upload_to='')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='run.run')),
            ],
        ),
    ]
