# Generated by Django 3.2.7 on 2022-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimporttubebatch',
            name='batch_type',
            field=models.CharField(choices=[('POOLING_BATCH', 'Pooling Batch'), ('RUN_BATCH', 'Run Batch')], default='POOLING_BATCH', max_length=32),
        ),
    ]
