# Generated by Django 3.2.7 on 2022-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubes', '0002_alter_tubebatchposition_unique_together'),
        ('data_importing', '0002_alter_fileimporttubebatch_batch_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('run_characteristics', models.JSONField()),
                ('tube_batches', models.ManyToManyField(to='tubes.TubeBatch')),
            ],
        ),
    ]
