
POOLING_BATCH = 'POOLING_BATCH'
RUN_BATCH = 'RUN_BATCH'

DISPLAY_POOLING_BATCH = 'Pooling Batch'
DISPLAY_RUN_BATCH = 'Run Batch'

TAG_POOLING_BATCH = DISPLAY_POOLING_BATCH
TAG_RUN_BATCH = DISPLAY_RUN_BATCH